# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod ALT, L, exec, hyprlock
bind = $mainMod ALT, M, exec, wlogout -p layer-shell
bind = $mainMod, Q, killactive,
bind = $mainMod, RETURN, exec, uwsm-app -- $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, space, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, S, layoutmsg, togglesplit # dwindle
