# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod ALT, L, exec, hyprlock
bind = $mainMod ALT, M, exec, wlogout -p layer-shell
bind = $mainMod, Q, killactive,
bind = $mainMod, RETURN, exec, uwsm-app -- $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, T, togglefloating,
bind = $mainMod, space, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, S, layoutmsg, togglesplit # dwindle
bind = SUPER, V, exec, cliphist list | vicinae dmenu | cliphist decode | wl-copy
# 区域截图：SUPER+SHIFT+S 拉框 → 存盘 + 复制到剪贴板 + satty 编辑
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" - | satty --filename - \
    --output-filename ~/Pictures/Screenshots/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png \
    --early-exit \
    --actions-on-enter save-to-clipboard \
    --save-after-copy \
    --copy-command 'wl-copy'
