#!/bin/bash

function get_repo_url() {
    cd $1 && git remote -v | grep origin | head -n 1 | awk '{print $2}'
}

repo_path=$1
repo_url=$(get_repo_url $repo_path)
git submodule add $repo_url $repo_path
