#!/bin/zsh

function mklnk(){
	if [[ -e $HOME/.$1 ]]; then
		mv $HOME/.$1 $HOME/.$1.bak
	fi
	ln -s $HOME/dotfiles/$1 $HOME/.$1
}


mklnk .gitconfig

mklnk .npmrc

mklnk .pip

mklnk .vim

mklnk .vimrc

mklnk .zshrc

source $HOME/.zshrc

