##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for window rules
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

xwayland {
    force_zero_scaling = true
}

dwindle {
    force_split = 2
    preserve_split = true
    smart_split = false
}

# anonymous rule syntax (Hyprland 0.53+)
layerrule = blur on, ignore_alpha 0, match:namespace vicinae
layerrule = no_anim on, match:namespace vicinae

# Waybar 毛玻璃
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.4, match:namespace waybar
