general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off HDMI-A-1 && hyprctl dispatch dpms off DP-1
    on-resume = hyprctl dispatch dpms on HDMI-A-1 && hyprctl dispatch dpms on DP-1
}

listener {
    timeout = 1800
    on-timeout = loginctl lock-session
}
