#!/bin/bash

ENV_DIR=${ENV_DIR:-$HOME/env}
MOUNT_DIR=${MOUNT_DIR:-$HOME}

for host in "$@"; do
    target_dir=$ENV_DIR/$host
    mkdir -p $target_dir
    sshfs -o allow_other,default_permissions $host:$MOUNT_DIR $target_dir
done
