#!/bin/bash
echo -e "$(uname -o) $(uname -r) $(uname -m) \e[34m$(date '+%Y-%m-%d %H:%M:%S%z')\e[0m"
echo "$(uptime)"
echo -e "welcome, \e[36m$(whoami)\e[0m! current dir [\e[33m$(uname -n)\e[0m]$(pwd)"
lsd
