#!/bin/sh
echo "$(uname -o) $(uname -r) $(uname -m)
Hello, $(whoami)! Now is $(date "+%Y-%m-%d %H:%M:%S%z")
System $(uptime)\nCurrent in [$(uname -n)]$(pwd)" | lolcat -ad 1 -S 128 -s 100 -p 5 -F 0.5
lsd
